config/routes.rb
require 'sidekiq/web'

MarkedUp::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :posts do
    resources :comments
    resources :votes
  end

  resources :users
  root to: 'pages#home'

  match '/about', to: 'pages#about', via: 'get'
  match '/address', to: 'users#address', via: 'get'
  match '/vote', to: 'posts#vote', via: 'post'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :post_id, presence: true
  validates :body, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :user_id, presence: true
  validates :body, presence: true, length: { maximum: 180 }
  validates :category, presence: true

  acts_as_voteable

  geocoded_by :address
  after_validation :geocode

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  belongs_to :user
  has_many :comments

  def self.search(search)
    if search
      where('body ILIKE ? OR address ILIKE ? OR category ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      self.all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  acts_as_voter

  validates :address, presence: true
  validates :first, presence: true
  validates :last, presence: true

  geocoded_by :address
  after_validation :geocode

  def full_name
    self.first + ' ' + self.last
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first, :last, :address]
  end

  def map_json(posts)
    json_data = []
    posts.each do |post|
      json_data << post.as_json(only: [:id,:category, :body, :address, :latitude, :longitude]).merge(count: post.votes.count)
    end
    json_data
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
    @comment.post = Post.find(params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:post_id])
    @comment.user = current_user
    if @comment.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @post = Post.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  respond_to :html, :json

  def index
    @post = Post.new
    @comment = Comment.new
    nearby_posts = Post.search(params[:search]).near([current_user.latitude, current_user.longitude],1).order("created_at").page(params[:page]).per(15)
    respond_to do |format|
      format.html { @posts = nearby_posts }
      format.json { render json: map_json(Post.near([current_user.latitude, current_user.longitude],1)) }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.json { render json: @post }
      end
    else
      respond_to do |format|
        format.html { render new_post_path }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @post = Post.near([current_user.latitude, current_user.longitude],1).find(params[:id])
    render json: @post.as_json(only: [:id,:category, :body, :address, :latitude, :longitude]).merge(count: @post.votes.count)
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path
    else
      render 'index'
      flash[:notice] = 'Error in deleting your post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:category, :body, :address, :latitude, :longitude)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = current_user
  end

  def address
    location = [current_user.latitude, current_user.longitude]
    respond_to do |format|
      format.html
      format.json { render json: location.as_json}
    end
  end

  def index
    @users = User.near([current_user.latitude, current_user.longitude],1)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  respond_to :html, :json

  def create
    @vote = Vote.new(vote_params)
    @vote.save
    respond_to do |format|
      format.html { redirect_to '/posts'}
      format.json { render json: @vote }
    end
  end

  private

  def vote_params
    { vote: true, voter_id: current_user.id, voteable_id: params[:post_id], voteable_type: 'Post' }
  end
end

app/views/comments/_form.html.erb
<%= simple_form_for [comment.post, comment] do |f| %>
 <%= f.error_notification %>
  <%= f.input :body, placeholder: 'Write a comment..', as: :text, required: true %>
  <%= f.button :submit, 'Submit', class: "button tiny secondary" %>
<% end %>

app/views/comments/new.html.erb
<%= render partial: '/comments/form', locals: {
        comment: @comment
      } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>MarkedUp</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= yield 'extra_footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<%= render 'shared/header' %>

<div class='row'>
  <div class="medium-12 small-centered columns text-center">
    <h1>About MarkedUp</h1>
    <p>MarkedUp is a geo-social network that allows people to voice concerns and/or praise for matters in their immediate local area. Always wanted to bolster support for a new bus-stop, park renovation, cafe, or well-known governmental issue in your neighborhood? Maybe you simply lost a personal item, or want to report on super-local news. Whatever your concern is, MarkedUp gives you the power to draw attention to your event or issue, and change your community for the better, in seconds.</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="off-canvas-wrap" data-offcanvas>
    <div class="inner-wrap">

      <%= render 'shared/mapheader' %>

      <div class='row'>
        <div class="medium-12 small-centered columns text-center">
          <h1>MarkedUp</h1>
          <p>[geo-social]</p>
        </div>
      </div>

      <% if user_signed_in? %>

      <div class='row'>
        <div class="medium-12 small-centered columns text-center">
         <div id='map'>
         </div>
       </div>
      </div>

      <div class='row'>
        <div class="medium-12 small-centered columns text-center">
         <p class='blank_space'></p>
        </div>
      </div>

      <aside class="right-off-canvas-menu">
        <iframe id='listview' src='/posts'>
        </iframe>
      </aside>

      <% else %>

      <div class='medium-12 small-centered columns text-center prompt'>
       <h2>Please Sign Up or Sign In:</h2>
         <ul class='splash'>
          <li><%= link_to 'Sign Up', '/users/sign_up' %></li>
          <li><%= link_to 'Sign In', '/users/sign_in' %></li>
        </ul>
      </div>

      <% end %>

    <div id='mapform'>
      <%= render 'shared/mapform' %>
    </div>

    <% content_for 'extra_footer' do %>
      <script>
        initializeMap();
      </script>
    <% end %>

    <a class="exit-off-canvas"></a>
  </div>
</div>

app/views/posts/_new.html.erb
 <%= simple_form_for @post do |f| %>
 <%= f.error_notification %>
  <%= f.input :category, collection: %w{ News Event Personal Parks/Public Works Entertainment Shops Restaurants Neighborhood Government Transportation Other }, required: true, prompt: 'Select a Category' %>
  <%= f.input :address, placeholder: 'e.g. 123 Candy Lane, Boston, MA 02145 or Prudential Center, Boston, MA', required: true %>
  <%= f.input :body, placeholder: 'Write a post..', as: :text, required: true %>
  <%= f.hidden_field :user_id, value: "#{current_user.id}", required: true %>
  <%= f.button :submit, 'Submit', class: 'button tiny radius' %>
<% end %>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <div class='postlist'>

    <div class='post_user'>
      <strong><%= "#{post.user.first}:"  %></strong>
    </div>

    <div class='post_category'>
      <%= post.category %>
    </div>

    <div class='post_body'>
      <%= post.body %>
    </div>

    <div class='post_address'>
      <%= post.address %>
    </div>

    <div class='post_votes_count'>
      <%= post.votes.count %>
    </div>

    <% if current_user == post.user %>
      <div class='delete_post'>
        <%= link_to 'Delete Your Post', post_path(post.id), method: 'delete' %>
      </div>
    <% end %>

    <button class= 'comment_toggle_button small round'>Comments</button>

    <div class='commenttoggle'>

    <%= button_to 'Vote', "/posts/#{post.id}/votes", class: 'vote_button button radius tiny alert' %>

    <% if post.comments.any? %>
      <p>Comments:</p>
        <% post.comments.each do |comment| %>
          <div class='commenter_color'>
            <%= "#{comment.user.first} " + "#{comment.user.last}" %><br>
          </div>

          <%= comment.body %><br><br>
        <% end
           end %>
      <p>Add a Comment:</p>
        <%= render partial: '/comments/form', locals: {
          comment: post.comments.build
        } %>

    </div>
  </div>
  <hr>
<% end %>

app/views/posts/index.html.erb
<div class='postlist'>

  <div class='general_area_post'>

    <h1>Write a General Area Post</h1>

    <%= render partial: 'new' %>

  </div>

  <hr>

  <h1 class='posts_index'>Posts in Your Area:</h1>

  <%= form_tag posts_path, :method => 'get', :id => "posts_search" do %>
    <p>
      <%= text_field_tag :search, params[:search], placeholder: 'Search posts in your area' %>
      <%= submit_tag "Search", :name => nil, class: 'button tiny radius' %>
    </p>
  <% end %>

  <div class='pagination'>
   <%= paginate @posts %>
  </div>

 <div id='posts'>
  <%= render 'posts' %>
 </div>

  <div class='pagination'>
   <%= paginate @posts %>
  </div>

</div>

app/views/posts/index.js.erb
$("#posts").html("<%= escape_javascript(render("posts")) %>");

app/views/shared/_header.html.erb
<nav class = 'top-bar' data-topbar>

<ul class="title-area">
    <li class="name">
      <h1><%= link_to "MarkedUp", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <% if signed_in? %>

  <section class="top-bar-section">
  <ul class = 'right'>
    <li><%= link_to "Hello, #{current_user.first}.", '/users/' + current_user.id.to_s %></li>
     <li class="divider"></li>
    <li><%= link_to "About", about_path %></li>
     <li class="divider"></li>
    <li><%= link_to "Users", users_path %></li>
     <li class="divider"></li>
    <li><%= link_to "Profile", '/users/' + current_user.id.to_s %></li>
     <li class="divider"></li>
    <li><%= link_to "Sign Out", '/users/sign_out', method: "delete" %></li>
    <li><a class="right-off-canvas-toggle button alert" href="#">View Post List</a></li>
  </ul>

  <% else %>

  <ul class = 'nav'>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Sign Up", '/users/sign_up' %></li>
    <li><%= link_to "Sign In", '/users/sign_in' %></li>
  </ul>
  <% end %>
  </section>
</nav>

app/views/shared/_mapform.html.erb
<%= simple_form_for(@post) do |f| %>
 <%= f.error_notification %>
  <%= f.input :category, collection: %w{ News Event Personal Parks/Public\ Works Entertainment Shops Restaurants Neighborhood Government Transportation Other }, required: true, prompt: 'Select a Category' %>
  <%= f.input :body, as: :text, placeholder: 'Write a post..', required: true %>
  <%= f.submit %>
<% end %>

app/views/shared/_mapheader.html.erb
<nav class = 'top-bar' data-topbar>

<ul class="title-area">
    <li class="name">
      <h1><%= link_to "MarkedUp", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <% if signed_in? %>

  <section class="top-bar-section">
  <ul class = 'right'>
    <li><%= link_to "Hello, #{current_user.first}.", '/users/' + current_user.id.to_s %></li>
     <li class="divider"></li>
    <li><%= link_to "About", about_path %></li>
     <li class="divider"></li>
    <li><%= link_to "Users", users_path %></li>
     <li class="divider"></li>
    <li><%= link_to "Profile", '/users/' + current_user.id.to_s %></li>
     <li class="divider"></li>
    <li><%= link_to "Sign Out", '/users/sign_out', method: "delete" %></li>
    <li><a class="right-off-canvas-toggle button alert" href="#">View Post List</a></li>
  </ul>

  <% else %>

  <ul class = 'nav'>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Sign Up", '/users/sign_up' %></li>
    <li><%= link_to "Sign In", '/users/sign_in' %></li>
  </ul>
  <% end %>
  </section>
</nav>

app/views/users/index.html.erb
<%=render 'shared/header' %>

<ul class='grid_6 text-center users'>
<h1><%= 'Users in Your Area' %></h1>
  <% @users.each do |user| %>
    <li><%= user.full_name + ' at ' + user.address  %></li>
    <li></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render 'shared/header' %>

<h1><%= @user.first + ' ' + @user.last + "'s Profile" %></h1>

<ul>
 <li><%= @user.email %></li>
 <li><%= @user.address %></li>
</ul>

<%= link_to "Change Password", edit_user_registration_path %>